# -*- coding: utf-8 -*-
"""25_11_24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8W4K0xTPtESZSL24Cj-TFxMGV6rUgGf
"""



"""# Class Method"""

class Employee:
  company_name = "Tech Solutions"

  def __init__(self, name, salary):
    self.name = name
    self.salary = salary

  def change_company_name(cls,new_name):
    cls.company_name = new_name

emp1 = Employee("Sam", 50000)
emp2 = Employee("Rahul", 60000)

print(Employee.company_name)
Employee.change_company_name("Future Tech")
print(Employee.company_name)

"""# Static Method"""

class MathOperations:
  def add(a,b):
    return a + b

  def subtract(a,b):
    return a-b

print(MathOperations.add(5,3))
print(MathOperations.subtract(10,4))

"""# Super Method()"""

class Parent:
  def __init__(self,name):
    self.name = name


  def greet(self):
    print(f"Hello, I am {self.name} from the Parent class")

class Child(Parent):
  def __init__(self,name,age):
    super().__init__(name)
    self.age = age

  def greet(self):
    super().greet()
    print(f"I am {self.age} years old from the Child Class")

child = Child("Sam", 10)
child.greet()

"""# Online Education Platform"""

class Student:
  def __init__(self,name):
    self.name = name
    self.courses = []

  def enroll_course(self,course):
    self.courses.append(course)
    course.enroll_student(self)
    print(f"{self.name} has been enrolled in {course.name}")

class Instructor:
  def __init__(self,name):
    self.name = name
    self.courses = []

  def assign_course(self,course):
    self.courses.append(course)
    print(f"{self.name} has assigned {course.name} as an instructor")


class Course(Student , Instructor):
  def __init__(self,name,duration):
    self.name = name
    self.duration = duration
    self.students = []

  def enroll_student(self,student):
    self.students.append(student)
    print(f"{student.name} has been enrolled in {self.name}")

  def show_course_details(self):
    print(f"Course Name: {self.name}")
    print(f"Duration: {self.duration}")
    print(f"Number of Students: {len(self.students)}")


course = Course("Python Programming","6_Months")
student = Student("Vaishnavi")
instructor = Instructor("Saurabh Sir")

course.enroll_student(student)
instructor.assign_course(course)
course.show_course_details()

